services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bcms-app
    volumes:
      - ./:/app
      - ./docker/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/logs:/var/log/caddy
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "443:443/udp"# HTTP/3
      - "5173:5173"  # Vite dev server
    restart: no
    env_file:
      - .env
    depends_on:
      - db
    tty: true
  node:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
  db:
    image: mysql:8.0
    container_name: bcms-mysql
    restart: no
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: